[versions]
template-minecraft-version = "1.21.1"
spigot = "1.21.1-R0.1-SNAPSHOT"
netty = "4.1.42.Final"
log4j = "2.17.0"
mountiplex = "3.18"
regionchangetracker = "1.3"
colorconversionhelper = "1.03"
softdependencylib = "1.03"
timings = "1.0.4"
gson = "2.8.9"
viaversion = "4.0.0"
vault = "1.7"
luckperms = "5.4"
protocollib = "4.4.0"
cloud_core = "2.0.0-rc.1"
cloud_minecraft = "2.0.0-beta.9"
commodore = "1.13"
adventure = "4.14.0"
adventure-platform-bukkit = "4.3.2-PR144-fix"
mockito = "2.22.0"
junit = "4.13"
shadow = "8.1.1"

[libraries]
spigot = { module = "org.spigotmc:spigot", version.ref = "spigot" }
spigot-api = { module = "org.spigotmc:spigot-api", version.ref = "spigot" }
netty-all = { module = "io.netty:netty-all", version.ref = "netty" }
log4j-api = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
mountiplex = { module = "com.bergerkiller.mountiplex:Mountiplex", version.ref = "mountiplex" }
cloud-core-bom = { module = "org.incendo:cloud-bom", version.ref = "cloud_core" }
cloud-minecraft-bom = { module = "org.incendo:cloud-minecraft-bom", version.ref = "cloud_minecraft" }
regionchangetracker = { module = "com.bergerkiller.bukkit.regionchangetracker:BKCommonLib-RegionChangeTracker-Core", version.ref = "regionchangetracker" }
colorconversionhelper = { module = "com.bergerkiller.bukkit.colorconversionhelper:BKCommonLib-ColorConversionHelper", version.ref = "colorconversionhelper" }
softdependency = { module = "com.bergerkiller.bukkit.softdependency:SoftDependency", version.ref = "softdependencylib" }
timings = { module = "co.aikar:minecraft-timings", version.ref = "timings" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
viaversion = { module = "com.viaversion:viaversion-api", version.ref = "viaversion" }
vault = { module = "com.github.MilkBowl:VaultAPI", version.ref = "vault" }
luckperms = { module = "net.luckperms:api", version.ref = "luckperms" }
protocollib = { module = "com.comphenix.protocol:ProtocolLib-API", version.ref = "protocollib" }
commodore = { module = "me.lucko:commodore", version.ref = "commodore" }
adventure-api = { module = "net.kyori:adventure-api", version.ref = "adventure" }
adventure-platform-bukkit = { module = "net.kyori:adventure-platform-bukkit", version.ref = "adventure-platform-bukkit" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
junit = { module = "junit:junit", version.ref = "junit" }

[plugins]
mountiplex = { id = "com.bergerkiller.mountiplex", version.ref = "mountiplex" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
